camera:
  name: kinect_camera # topic
  parent: front_camera_link
  hz: 30
  horizontal_fov: 1.089
  depth_min: 0.1
  depth_max: 100.0
  image_width: 640
  image_height: 480
  clip_near: 0.2
  clip_far: 10.0

lidar:
  name: ouster
  parent: lidar_connector_link
  topic: ouster_points
  frame_id: ouster
  hz: 10
  lasers: 32
  samples: 512
  collision_range: 0.3
  min_range: 0.9
  max_range: 130.0
  noise: 0.008
  min_angle: -3.1415926535897931
  max_angle: 3.1415926535897931
  gpu: false

imu:
  name: imu
  parent: base_link
  topic: /imu_hpc
  frame_id: ouster
  hz: 100
  updatehz: 100

  xOffset: 0.0
  yOffset: 0.0
  zOffset: 0.0

  rollOffset: 0.0
  pitchOffset: 0.0
  yawOffset: 0.0
  gaussianNoise: 0.0

gps:
  name: gps
  parent: base_link
  topic: gps/fix
  hz: 10

  # gaussian noise
  horizontal_mean: 0.0
  horizontal_stddev: 0.0
  vertical_mean: 0.0
  vertical_stddev: 0.0